# Setup
title: AFE
description: Kişisel blog
url: https://afeblog.github.io
avatar: /avatar.png
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Ahmet Tunahan Demir
  links:
    - https://github.com/AFEGaming
google_site_verification: xxxxx
lang: tr

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Ahmet
  url: https://github.com/AFEGaming
  email: gjawamaz@anonaddy.me

months_tr:
  - Ocak
  - Şubat
  - Mart
  - Nisan
  - Mayıs
  - Haziran
  - Temmuz
  - Ağustos
  - Eylül
  - Ekim
  - Kasım
  - Aralık
